### ISSUE TITLE
Two issues with underlying IRS data formats

### ISSUE THREAD

**Issue by ashahidinejad** [mathewhauer/irs-migration-replication#1]
First, I wanted to thank the authors for providing this public good!

For users, I wanted to note two potential issues with the data, according to my understanding of it.

1. Unlike for most files, some inflow files do not properly format leading zeros for states and counties. I noticed this for the 1998 inflow files for WV and PA. It affects the final dataset in that it generates erroneously coded county codes.

``` R
library(data.table)
dt <- data.table(read.csv('county_migration_data.csv'))
print(dt[dt$destination<1000 | dt$origin<1000,])

     origin destination X1990 X1991 X1992 X1993 X1994 X1995 X1996 X1997 X1998 X1999 X2000 X2001 X2002 X2003 X2004 X2005 X2006 X2007 X2008 X2009 X2010
  1:    101       42101     0     0     0     0     0     0     0     0    47     0     0     0     0     0     0     0     0     0     0     0     0
  2:    101        4217     0     0     0     0     0     0     0     0    22     0     0     0     0     0     0     0     0     0     0     0     0
  3:    101        4229     0     0     0     0     0     0     0     0    11     0     0     0     0     0     0     0     0     0     0     0     0
  4:    101         423     0     0     0     0     0     0     0     0    28     0     0     0     0     0     0     0     0     0     0     0     0
  5:    101        4245     0     0     0     0     0     0     0     0    25     0     0     0     0     0     0     0     0     0     0     0     0
 ---                                                                                                                                                 
661:   5491         541     0     0     0     0     0     0     0     0    26     0     0     0     0     0     0     0     0     0     0     0     0
662:   5497         541     0     0     0     0     0     0     0     0    26     0     0     0     0     0     0     0     0     0     0     0     0
663:   5497         547     0     0     0     0     0     0     0     0    18     0     0     0     0     0     0     0     0     0     0     0     0
664:   5525         423     0     0     0     0     0     0     0     0    27     0     0     0     0     0     0     0     0     0     0     0     0
665:   5579         423     0     0     0     0     0     0     0     0    30     0     0     0     0     0     0     0     0     0     0     0     0
```

2. Judging from the aggregate counts in the final dataset across years, there seems to be some leakage in the 1996 bucket of censored movers '99999'.
```R
yearCols <- colnames(dt)[substr(colnames(dt),1,1)=='X']
years    <- as.integer(substr(yearCols,2,5))

par(mfrow=c(2,2))
plot(years, colSums(dt[,                          ..yearCols]), type='l',ylab='Total')
plot(years, colSums(dt[dt$destination==dt$origin, ..yearCols]), type='l',ylab='Non-Movers')
plot(years, colSums(dt[dt$destination=='99999',   ..yearCols]), type='l',ylab='Censored Movers')
plot(years, colSums(dt[dt$destination!='99999'& 
                       dt$destination!=dt$origin, ..yearCols]), type='l',ylab='Non-Censored Movers')
``` 

![image](https://user-images.githubusercontent.com/11236348/59529027-81cdb180-8ea5-11e9-8ec9-08dbc772d748.png)

**Comment by mathewhauer** [comment]
Thanks! I'll take a look at the 1998 datafile next week. Thanks for letting me know!


-------------------------
Mathew Hauer, PhD

Assistant Professor, Department of Sociology

Center for Demography and Population Health

605 Bellamy Building, 113 Collegiate Loop
Florida State University, Tallahassee, FL, 32306
850-644-7103


________________________________

**Comment by mathewhauer** [comment]
So I found the problems and fixed them. There were two separate problems in the IRS migration data themselves.

1) Regarding the origin's/destination's with odd FIPS codes. For some reason, the PA and WV excel files provided by the IRS do not explicitly declare the state and county variables as characters.
![PA-IRS](https://user-images.githubusercontent.com/16724401/59557010-8c1ea700-8f9c-11e9-864d-ddeb1fb99e2f.PNG)

Notice the county column starts with a '0' instead of a '000'.

I explicitly declared those columns as characters and used `str_pad()` to ensure the leading zeroes are included.

2) Regarding the leakage in the 1996 bucket. This is, again, a weird oddity in the IRS migration data. For some unknown reason, the IRS out-migration files randomly capitalize the filenames for some states and only for the out-migration files.

![IRS-cap](https://user-images.githubusercontent.com/16724401/59557028-fa636980-8f9c-11e9-9b89-ce3c86e322ef.PNG)

When pulling the files into R, the code now declares `ignore.case=T` and the files are all brought in correctly.

```
dt <- data.table(read.csv('DATA-PROCESSED/county_migration_data.csv'))
print(dt[dt$destination<1000 | dt$origin<1000,])

> Empty data.table (0 rows and 23 cols): origin,destination,X1990,X1991,X1992,X1993...
```

Shows there are no origins with less than 5 digits. Thus, the problem with PA and WV in 1998 should now be fixed.

```
yearCols <- colnames(dt)[substr(colnames(dt),1,1)=='X']
years    <- as.integer(substr(yearCols,2,5))

par(mfrow=c(2,2))
plot(years, colSums(dt[,                          ..yearCols]), type='l',ylab='Total')
plot(years, colSums(dt[dt$destination==dt$origin, ..yearCols]), type='l',ylab='Non-Movers')
plot(years, colSums(dt[dt$destination=='99999',   ..yearCols]), type='l',ylab='Censored Movers')
plot(years, colSums(dt[dt$destination!='99999'& 
                         dt$destination!=dt$origin, ..yearCols]), type='l',ylab='Non-Censored Movers')
```


![Rplot](https://user-images.githubusercontent.com/16724401/59557641-9ba5ec00-8fac-11e9-9978-df2abc868d00.png)
